# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46767f0748503c7555d4a4801fb0a7eff80424b656129f6052845e8ea576cd9ec2708da1ff7b54e546f48ee45920878d9bdebf2edc411f3ac05011bd335ad901

test:
  secret_key_base: ae1100da663131e2c2c4742f63b200e2adf379963188a64bba3349416fd95479b082309373994d56218f19e2a0a2e258c92205326ddbebdf2f0fba452e743e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
